# Generated by Django 3.1.7 on 2025-05-30 10:04

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210618_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='profile_pic',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='authors/default_avatar.jpg', force_format=None, keep_meta=True, null=True, quality=100, size=[50, 80], upload_to='authors'),
        ),
    ]
